apiVersion: v1
kind: Service
metadata:
  labels:
    component: hazelcast
  name: hazelcast
spec:
  ports:
  - name: hazelcast
    port: 5701
    targetPort: 5701
  selector:
    component: hazelcast
  clusterIP: None
  type: ClusterIP
---

