kind: Service
apiVersion: v1
metadata:
  name: remote-view
  labels:
    app: remote-view
spec:
  selector:
    app: remote-view
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: remote-view
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: remote-view
        component: hazelcast
    spec:
      containers:
        - name: remote-view
          image: docker.sebastian-daschner.com/web-view:1
          imagePullPolicy: Always
          ports:
            - containerPort: 5701
              name: hazelcast
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always
---