kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: remote-datasource
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: remote-datasource
        component: hazelcast
    spec:
      containers:
        - name: remote-datasource
          image: docker.sebastian-daschner.com/datasource:1
          imagePullPolicy: Always
          ports:
            - containerPort: 5701
              name: hazelcast
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always
---