kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: remote-parser
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: remote-parser
        component: hazelcast
    spec:
      containers:
        - name: remote-parser
          image: docker.sebastian-daschner.com/parser:1
          imagePullPolicy: Always
          ports:
            - containerPort: 5701
              name: hazelcast
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always
---